### ISSUE TITLE
error install gem

### ISSUE THREAD

**Issue by juanbits** [bcrypt-ruby/bcrypt-ruby#101]
hi i use:
ruby 2.1.3p242 (2014-09-19) [x86_64-linux-gnu]

and:
gem: 2.1.11

i try install this gem but i receive an error:
Building native extensions.  This could take a while...
ERROR:  Error installing bcrypt:
    ERROR: Failed to build gem native extension.

```
/usr/bin/ruby2.1 extconf.rb
```

checking for ruby/util.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.1
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/2.1.0/mkmf.rb:587:in`try_cpp'
    from /usr/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
    from /usr/lib/ruby/2.1.0/mkmf.rb:918:in`block in checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in`open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in`open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:917:in`checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
    from extconf.rb:14:in`<main>'

Gem files will remain installed in /var/lib/gems/2.1.0/gems/bcrypt-3.1.7 for inspection.
Results logged to /var/lib/gems/2.1.0/gems/bcrypt-3.1.7/ext/mri/gem_make.out

**Comment by kalashnikovisme** [comment]
Having similar problem with message

```shell
ERROR:  Error installing bcrypt:
	ERROR: Failed to build gem native extension.

    current directory: /home/user_name/.rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.10/ext/mri
/home/user_name/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160106-20783-htzjgt.rb extconf.rb
creating Makefile

current directory: /home/user_name/.rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.10/ext/mri
make "DESTDIR=" clean

current directory: /home/user_name/.rvm/gems/ruby-2.3.0/gems/bcrypt-3.1.10/ext/mri
make "DESTDIR="
compiling crypt.c
compiling wrapper.c
compiling crypt_gensalt.c
compiling crypt_blowfish.c
compiling bcrypt_ext.c
linking shared-object bcrypt_ext.so
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [bcrypt_ext.so] Error 1

make failed, exit code 2
```

**Comment by kalashnikovisme** [comment]
solved by 

```shell
sudo aptitude install libgmp-dev
```

**Comment by wacaw** [comment]
@kalashnikovisme thanks!

**Comment by minibrary** [comment]
Guys, it's been passed post, but another reason I got, build-essential is missing.

```
sudo apt-get install build-essential
```

This fixes and able install.

**Comment by cheezyo** [comment]
Hi I am still struggling with this issue. Could you please help.


I try the solution you guy gave it tells me everything is up to date:

sudo apt install libgmp-dev
libgmp-dev is already the newest version (2:6.1.0+dfsg-2).

sudo apt-get install build-essential
build-essential is already the newest version (12.1ubuntu2).

When i try to install bcrypt i get the same error as mentioned above:

cezar@cezar:/var/lib/gems/2.3.0/gems$ sudo gem install bcrypt -v '3.1.11'

Building native extensions.  This could take a while...
ERROR:  Error installing bcrypt:
ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/bcrypt-3.1.11/ext/mri
/usr/bin/ruby2.3 -r ./siteconf20161015-5474-4zz8lw.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/bcrypt-3.1.11 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/bcrypt-3.1.11/gem_make.out


Anyone that can help me. I pretty new to developing rails on Linux.

**Comment by mkaito** [comment]
@cheezyo 

    mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You need to install the ruby development headers. Usually `ruby-dev` or `ruby2.4-dev` or somesuch, depending on what repo you're installing from.

**Comment by jomarocas** [comment]
sudo apt install ruby-dev for solution this
