### ISSUE TITLE
Performance test in README.md misleading

### ISSUE THREAD

**Issue by mipearson** [bcrypt-ruby/bcrypt-ruby#105]
Hi,

In our own testing, using bcrypt with the default cost of 10 (on modern hardware) we saw much slower encryption times than the performance test in the readme would suggest. Our own benches gave us about 20 passwords/sec at 10 and 80 passwords/sec at 8.

Based on the age on that section of the README (< 2007) and the performance seen, I'm going to guess the test was performed at a drastically lower cost, even perhaps a cost of 1.

Can the README please be updated to reflect the nature of the benchmark?

**Comment by mipearson** [comment]
... also mentioning that the cost factor is in fact an exponent would be helpful.

**Comment by nwjsmith** [comment]
@mipearson is the benchmark you're referring to the comparison to `md5`?

**Comment by mipearson** [comment]
Woah, this an old one. Looking at the readme - yeah, I think it's this section I was referring to:

> If an attacker was using Ruby to check each password, they could check ~140,000 passwords a second with MD5 but only ~450 passwords a second with bcrypt().

**Comment by nwjsmith** [comment]
@mipearson ok, I've reproduced the benchmark and it looks like the cost was set to one. Clarified the documentation in https://github.com/bcrypt-ruby/bcrypt-ruby/pull/264
