### ISSUE TITLE
Ruby 2.2.0 Issue with FormEncoded Parameters

### ISSUE THREAD

**Issue by davestevens** [bcrypt-ruby/bcrypt-ruby#109]
**NB: Ruby 2.2.2 fixes this**

We're currently using `Devise` to perform authentication with our App. We upgraded to Ruby 2.2.0 yesterday and noticed that we are unable to log in if there are certain characters in a users password.

I've been digging into the BCrypt code and the problem seems to be somewhere in the `mri` interface. `StringValuePtr(key)` within the function `bc_crypt` reports an incorrect string/length which leads to trailing characters being used within the string which BCrypt is using.

After attempting to replicate this problem I found that it was based around the Parameters coming into our Rails app. After further digging it seems to only be an issue with FormEncoded payloads and only `url_encoded` characters cause this problem.

Its as though Rails is creating a String object which allocates the space for the url encoded characters and then continues to use this same `RString` object once it is no longer a url encoded string, resulting in `StringValuePtr` returning garbage at the end of the string being passed into `crypt_ra` which then breaks BCrypt.

I assume that this is more of a Ruby issue than a BCrypt, any help would be greatly appreciated!

If you need any more information / a test project setting up let me know.

Example:
FormData into app:
`{ user: "email@example.com", password: "abcd/efgh" }`
This is passed through to Devise, `password` is passed to `valid_password?` in `/lib/devise/models/database_authenticatable.rb` which calls `hash_secret` with the password. Within Ruby `password` is a `String` and behaves exactly how it should do. It is only once it gets into the `C` code that it breaks.
`strlen(StringValuePtr(key))` returns `14` and includes garbage on the end of the string.
`RSTRING_LEN(key)` returns `9`.
(**NB** When changed to a json payload this is no longer an issue)

This currently fixes the problem I have been seeing

``` c
void terminate_string_value_ptr(VALUE key) {
  long length;
  char *string;

  length = RSTRING_LEN(key);
  string = RSTRING_PTR(key);

  string[length] = '\0';
}
```

``` c
static VALUE bc_crypt(VALUE self, VALUE key, VALUE setting) {
...
    if(NIL_P(key) || NIL_P(setting)) {
      return Qnil;
    }
...

    // Fixes RString pointer to terminal string.
    terminate_string_value_ptr(key);
    terminate_string_value_ptr(setting);

...
    value = crypt_ra(
        NIL_P(key) ? NULL : StringValuePtr(key),
        NIL_P(setting) ? NULL : StringValuePtr(setting),
        &data,
        &size);
```

**Comment by tmm1** [comment]
> string[length] = '\0';

I don't think this is safe to do, since you're not guaranteed that space exists for the null byte. It sounds like we need a version of `crypt_ra` that accepts a string length.

**Comment by tmm1** [comment]
Alternatively, we would need to make a copy of the string into a new buffer that has space for the null byte. This could probably be stack allocated.

**Comment by davestevens** [comment]
Good point, that code I put up is just something that ended up working for the example while I was working with it.
In our production code I am making a copy of the password string from the params hash and passing that though (which also fixes it as the new string has the correct length).

**Comment by davestevens** [comment]
After some further digging I was able to replicate the problem I was seeing without Rails and with minimal setup. https://gist.github.com/davestevens/a9187de713a32cb005b1

**Comment by Hamled** [comment]
Before I checked and found this issue, some of my debugging led me to the StringValueCStr() function, which seems very similar to StringValuePtr().
However, whatever conversion work it performs actually seems to involve checking the length, so the resulting C-style string is properly terminated, I believe. If someone with more experience in Ruby's C API can confirm that, I think it using that function be the cleanest change to fix this issue.

**Comment by davestevens** [comment]
I just had a look at that function and it does look like that would resolve this problem.
I will have a look at using this in place of the StringValuePtr function.
This is no longer a problem in Ruby 2.2.2.

**Comment by Trevoke** [comment]
@davestevens Can you edit the top post and add the "Ruby 2.2.2 fixes this" note ?

**Comment by davestevens** [comment]
@Trevoke I've just added that.

**Comment by skylar** [comment]
FYI, I saw a similar problem today on Ruby 2.6.6 and bcrypt 3.1.11.  It seems resolved in the latest version of bcypt. Perhaps it was solved by a similar MR.

**Comment by davestevens** [comment]
I would say its fine to close after seven years!
