### ISSUE TITLE
Possible security issue: null bytes are allowed in the input stream to hash

### ISSUE THREAD

**Issue by mlen** [bcrypt-ruby/bcrypt-ruby#115]
Bcrypt is designed to be `crypt(3)` compatible and it takes NUL-terminated strings as arguments. Ruby strings can include NUL bytes and should be checked before passing them to C functions.

``` ruby
[1] pry(main)> require 'bcrypt'
=> true
[2] pry(main)> BCrypt::Password.create("as\0df") == "as"
=> true
```

The last line returns `true`, while obviously these two passwords are not the same.

**Comment by reedloden** [comment]
See also #114.
