### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by vishnurkrishnan** [bcrypt-ruby/bcrypt-ruby#148]
I am using devise gem for authentication, current rails version is 3.2.22, so my password have some special character like **'admin@123**' , after upgrade to ruby 2.2.0 i couldn't login with that credentials but that allows me to login after removing that '@', also '**password@123**' is working. i think by default devise is using this bcrypt

current version which am using

devise (2.2.1)
bcrypt-ruby (3.0.1)
orm_adapter (> 0.1)
railties (> 3.1)
warden (~> 1.2.1)

**Comment by tomekw** [comment]
@vishnurkrishnan you want to say that after upgrading the Ruby the old hashes became invalid?
