### ISSUE TITLE
Rails 6.1.3.1 - BCrypt::Errors::InvalidHash Exception: invalid hash

### ISSUE THREAD

**Issue by JamesAnthonyPino** [bcrypt-ruby/bcrypt-ruby#254]
I recently updated a project to Rails 6.1.3.1 and one of my controllers is now throwing the following:
`BCrypt::Errors::InvalidHash Exception: invalid hash`

As confirmation, I have tested this in the Rails console with various values and it always throws the same` exception. When I switch back to Rails 5.x, it works as expected.

I am at the latest version, 3.1.16, and have even tried to downgrade to previous version with the same result.

**Comment by athix** [comment]
@JamesAnthonyPino can you create a new rails app and try to replicate the bug with as minimal an amount of code possible? This would help isolate the issue, and provide an easy way for the maintainers to investigate further.

**Comment by JamesAnthonyPino** [comment]
@athix It works when I use a value of a specific length. It may have been a breaking change. In any case, I will close this.
