### ISSUE TITLE
Cannot install bcrypt on Windows 10

### ISSUE THREAD

**Issue by EmanuelRodriguezBedeman** [bcrypt-ruby/bcrypt-ruby#258]
Hello! I'm trying to install the gem "Devise" which seems to require the "bcrypt" gem and I'm getting the next error: 

> Installing bcrypt 3.1.17 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
> current directory:
> C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.17/ext/mri
> C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
> ./siteconf20220401-17988-s4yhet.rb extconf.rb
> creating Makefile
> 
> current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.17/ext/mri
> make DESTDIR\= clean
> 
> current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.17/ext/mri
> make DESTDIR\=
> generating bcrypt_ext-x64-mingw-ucrt.def
> compiling bcrypt_ext.c
> make: gcc: No such file or directory
> make: *** [Makefile:246: bcrypt_ext.o] Error 127
> 
> make failed, exit code 2
> 
> Gem files will remain installed in
> C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bcrypt-3.1.17 for inspection.
> Results logged to
> C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/bcrypt-3.1.17/gem_make.out
> 
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:44:in `block in make'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `each'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `make'
> C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:63:in `block in
> build'
>   C:/Ruby31-x64/lib/ruby/3.1.0/tempfile.rb:317:in `open'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
> C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
> build_extensions'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
>   C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in
> `build_extensions'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in
> `install'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
> `install_from_spec'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
> `do_install'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
> `block in worker_pool'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
>   C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
> C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
> create_threads'
> 
> An error occurred while installing bcrypt (3.1.17), and Bundler cannot continue.
> 
> In Gemfile:
>   devise was resolved to 4.8.1, which depends on
>     bcrypt
> 

I'm on Windows 10, using:

-Ruby v3.1.1p18
-Rails 7.0.2.3

**Comment by tjschuck** [comment]
It looks like you're missing `gcc`.  Did you install Ruby via https://rubyinstaller.org?  If so, it looks like you didn't include the DevKit, or didn't install the DevKit properly.  See the "With Development Kit?" section here: https://rubyinstaller.org/downloads/

Try (re)installing the DevKit.

**Comment by EmanuelRodriguezBedeman** [comment]
> It looks like you're missing `gcc`. Did you install Ruby via https://rubyinstaller.org? If so, it looks like you didn't include the DevKit, or didn't install the DevKit properly. See the "With Development Kit?" section here: https://rubyinstaller.org/downloads/
> 
> Try (re)installing the DevKit.

Hello chuck, I downloaded and installed ruby though rubyinstaller.org and even tried to do a clean re-install making sure that DevKit is installed and still getting the same error.

**Comment by tjschuck** [comment]
@EmanuelRodriguezBedeman Unfortunately, bcrypt-ruby can be compiled and run on Windows/Ruby 3.1 in other contexts (see https://github.com/bcrypt-ruby/bcrypt-ruby/runs/5578834403, for example), so it seems like this is an issue with your local environment.

I recommend trying the rubyinstaller mailing list — they're very helpful when it comes to troubleshooting these installation issues: https://groups.google.com/g/rubyinstaller

**Comment by EmanuelRodriguezBedeman** [comment]
Will check it out, thank you very much Chuck!
