### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' M1 macbook issue.

### ISSUE THREAD

**Issue by iamhamzaawan** [bcrypt-ruby/bcrypt-ruby#259]
I am getting the following error after creating user after integrating devise in my project.

`LoadError (dlopen(/Users/hamzaaamir/.rvm/gems/ruby-2.6.8/gems/bcrypt-3.1.17/lib/bcrypt_ext.bundle, 0x0009): tried: '/Users/hamzaaamir/.rvm/gems/ruby-2.6.8/gems/bcrypt-3.1.17/lib/bcrypt_ext.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/hamzaaamir/.rvm/gems/ruby-2.6.8/gems/bcrypt-3.1.17/lib/bcrypt_ext.bundle)`

Can anyone help me solve this issue for m1 macbook?

**Comment by naveed-ahmad** [comment]
`arch -arm64 gem install bcrypt` works for me.
