### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nwjsmith** [bcrypt-ruby/bcrypt-ruby#262]
I hate to be that guy, but the [GVL unlock](https://github.com/bcrypt-ruby/bcrypt-ruby/pull/260) will fix a performance issue for our team. Let me know if you'd like me to write up the `CHANGELOG` and version bump and I'll get a PR open.

Thanks for maintaining such an important library!

**Comment by tjschuck** [comment]
@nwjsmith 👍 — when you open the PR, please include a changelog entry for your `ext/mri/bcrypt_ext.c` changes in https://github.com/bcrypt-ruby/bcrypt-ruby/pull/261 and I'll pull both of them into the release.  Thanks!

**Comment by nwjsmith** [comment]
@tjschuck all set in #263 thank you!

**Comment by tjschuck** [comment]
Pushed 3.1.18: https://rubygems.org/gems/bcrypt/versions

Thanks, @nwjsmith!
