### ISSUE TITLE
Password presence validation bizarre behaviour

### ISSUE THREAD

**Issue by chiaraani** [bcrypt-ruby/bcrypt-ruby#277]
```ruby
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
end
```
```ruby
created_user = User.create!(name: "Foo", password: "abc123")
created_user.update!(name: "Bar", password: "")
# => true

found_user = User.last
found_user.update!(name: "Other", password: "")
# =>  Validation failed: Password can't be blank (ActiveRecord::RecordInvalid)
```
More info on:
[Why would `has_secure_password` suppress password validation on update, but only if the object is newly created?](https://stackoverflow.com/questions/78654116/why-would-has-secure-password-suppress-password-validation-on-update-but-only)

May I ask this behaviour is intended or it's a bug?

**Comment by tjschuck** [comment]
> May I ask this behaviour is intended or it's a bug?

`has_secure_password` is part of Rails, so you'd have to file an issue on https://github.com/rails/rails to see what the intended behavior is.  `has_secure_password` uses bcrypt-ruby under the hood, but those validations are not from bcrypt-ruby — they're provided by Rails.
