### ISSUE TITLE
Add OS X to the Travis matrix

### ISSUE THREAD

**Issue by tjschuck** [bcrypt-ruby/bcrypt-ruby#94]
[Travis now supports testing against multiple OSes](http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/).  Currently only includes Linux and OS X.

Right now it's just in beta and therefore feature-flagged, but this issue is to leave a reminder for future-us about it.  Once it's publicly available (or if someone wants to email about it), we should add it to our Travis matrix.

**Comment by nwjsmith** [comment]
I think it's safe to close this, tests are run on macOS, Windows, and Linux in GitHub Actions now
